### ISSUE TITLE
[Suggestion] Copy/Paste Issue

### ISSUE THREAD

**Issue by burhan** [ember-learn/super-rentals#162]
There is an issue when copy-pasting code from the official website in VSCode, namely the `-` (dash) is being copied as `\U+2013` which is the `n-dash` character (ref: https://www.compart.com/en/unicode/U+2013).

VSCode will highlight this:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/603112/180664646-e96bc5d0-c6e8-428c-8c6a-d914ca8a09c1.png">

If your editor doesn't warn about this, you'll notice the tests are failing, but without indication as to why its failing:

```
not ok 16 Chrome 103.0 - [39 ms] - Integration | Component | rental/detailed: it renders detailed information about a rental property
    ---
        actual: >
            Type: Standalone - Estate
        expected: >
            Standalone – Estate
        stack: >
                at DOMAssertions.includesText (http://localhost:7357/assets/test-support.js:9731:12)
                at DOMAssertions.containsText (http://localhost:7357/assets/test-support.js:9741:19)
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:406:42)
        message: >
            Element article .detail.type has text containing "Standalone – Estate"
        negative: >
            false
        browser log: |
    ...
```

I think this should be added as a warning as it seems to be specific to VSCode (as WebStorm doesn't have this problem).

**Comment by MinThaMie** [comment]
I think the test/tutorial has updated in later versions and I cannot find this text in any of the tests in the current tutorial. So I will close this issue :)
