### ISSUE TITLE
this.namespace = '/api' causes Mirage to crash.

### ISSUE THREAD

**Issue by Rup1** [ember-learn/super-rentals#78]
Hi,

While going through the `Building a complex component` part of the tutorial, the app start crashing with the following message in the console:
```

assert.js:35 Mirage: Your Ember app tried to GET '/rentals',
         but there was no route defined to handle this request.
         Define a route that matches this path in your
         mirage/config.js file. Did you forget to add your namespace?

MirageError @ assert.js:35
assert @ assert.js:9
unhandledRequest @ server.js:47
handleRequest @ pretender.js:397
send @ pretender.js:164
send @ jquery.js:9566
ajax @ jquery.js:9173
_ajaxRequest @ rest.js:630
(anonymous) @ rest.js:626
initializePromise @ rsvp.js:453
Promise @ rsvp.js:919
ajax @ rest.js:609
findAll @ rest.js:359
_findAll @ -private.js:8768
_fetchAll @ -private.js:11464
findAll @ -private.js:11432
filterByCity @ rentals.js:14
join @ backburner.js:576
run.join @ ember-metal.js:4309
(anonymous) @ action.js:390
exports.flaggedInstrument @ ember-metal.js:3730
(anonymous) @ action.js:389
init @ list-filter.js:16
superWrapper @ ember-utils.js:426
Class @ core_object.js:113
_ClassMixinProps.create @ core_object.js:283
create @ container.js:391
create @ container.js:135
create @ curly.js:178
(anonymous) @ runtime.js:1671
evaluate @ runtime.js:70
next @ runtime.js:7244
next @ runtime.js:7315
RootState.render @ renderer.js:62
exports.runInTransaction @ ember-metal.js:641
_renderRoots @ renderer.js:341
_renderRootsTransaction @ renderer.js:379
_renderRoot @ renderer.js:299
_appendDefinition @ renderer.js:209
appendOutletView @ renderer.js:192
invoke @ backburner.js:272
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:455
run @ backburner.js:539
join @ backburner.js:546
run.join @ ember-metal.js:4309
(anonymous) @ ember-metal.js:4382
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
assert.js:36 MirageError {description: "Mirage: undefined", fileName: undefined, lineNumber: undefined, message: "Mirage: Your Ember app tried to GET '/rentals',↵  …ig.js file. Did you forget to add your namespace?", name: "Error", …}
MirageError @ assert.js:36
assert @ assert.js:9
unhandledRequest @ server.js:47
handleRequest @ pretender.js:397
send @ pretender.js:164
send @ jquery.js:9566
ajax @ jquery.js:9173
_ajaxRequest @ rest.js:630
(anonymous) @ rest.js:626
initializePromise @ rsvp.js:453
Promise @ rsvp.js:919
ajax @ rest.js:609
findAll @ rest.js:359
_findAll @ -private.js:8768
_fetchAll @ -private.js:11464
findAll @ -private.js:11432
filterByCity @ rentals.js:14
join @ backburner.js:576
run.join @ ember-metal.js:4309
(anonymous) @ action.js:390
exports.flaggedInstrument @ ember-metal.js:3730
(anonymous) @ action.js:389
init @ list-filter.js:16
superWrapper @ ember-utils.js:426
Class @ core_object.js:113
_ClassMixinProps.create @ core_object.js:283
create @ container.js:391
create @ container.js:135
create @ curly.js:178
(anonymous) @ runtime.js:1671
evaluate @ runtime.js:70
next @ runtime.js:7244
next @ runtime.js:7315
RootState.render @ renderer.js:62
exports.runInTransaction @ ember-metal.js:641
_renderRoots @ renderer.js:341
_renderRootsTransaction @ renderer.js:379
_renderRoot @ renderer.js:299
_appendDefinition @ renderer.js:209
appendOutletView @ renderer.js:192
invoke @ backburner.js:272
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:455
run @ backburner.js:539
join @ backburner.js:546
run.join @ ember-metal.js:4309
(anonymous) @ ember-metal.js:4382
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
ember-metal.js:3927 Mirage: Your Ember app tried to GET '/rentals',
         but there was no route defined to handle this request.
         Define a route that matches this path in your
         mirage/config.js file. Did you forget to add your namespace?
Mirage: Error: Your Ember app tried to GET '/rentals',
         but there was no route defined to handle this request.
         Define a route that matches this path in your
         mirage/config.js file. Did you forget to add your namespace?
    at new MirageError (http://localhost:4200/assets/vendor.js:122006:21)
    at assert (http://localhost:4200/assets/vendor.js:121992:13)
    at Pretender.unhandledRequest (http://localhost:4200/assets/vendor.js:127122:46)
    at Pretender.handleRequest (http://localhost:4200/assets/vendor.js:67202:14)
    at FakeRequest.send (http://localhost:4200/assets/vendor.js:66969:17)
    at Object.send (http://localhost:4200/assets/vendor.js:9907:10)
    at Function.ajax (http://localhost:4200/assets/vendor.js:9514:15)
    at Class._ajaxRequest (http://localhost:4200/assets/vendor.js:172229:15)
    at http://localhost:4200/assets/vendor.js:172225:17
    at initializePromise (http://localhost:4200/assets/vendor.js:63620:7)
```

Removing `this.namespace = '/api';` Fixes this and everything works fine again. Why is this happening?

**Comment by Rup1** [comment]
Apologies, after staring at this problem for an hour, I found the problem right after opening this issue. I forgot to include the namespace in the JSONAPIAdapter.
